### ISSUE TITLE
Raknet Server Crash

### ISSUE THREAD

**Issue by EinBexiii** [NukkitX/FakeInventories#4]
20:38:55 [FATAL] [Network] Stopped interface cn.nukkit.network.RakNetInterface due to java.lang.NullPointerException
        at com.nukkitx.fakeinventories.inventory.FakeInventory.onClose(FakeInventory.java:83)
        at cn.nukkit.inventory.BaseInventory.close(BaseInventory.java:436)
        at cn.nukkit.Player.removeWindow(Player.java:4611)
        at cn.nukkit.Player.removeAllWindows(Player.java:4697)
        at cn.nukkit.Player.close(Player.java:3672)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:70)
        at cn.nukkit.network.Network.processInterfaces(Network.java:154)
        at cn.nukkit.Server.tick(Server.java:1151)
        at cn.nukkit.Server.tickProcessor(Server.java:931)
        at cn.nukkit.Server.start(Server.java:899)
        at cn.nukkit.Server.<init>(Server.java:580)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)

**Comment by Mcayear** [comment]
I also encountered this problem.
